### ISSUE TITLE
Integrations via IPSME 

### ISSUE THREAD

**Issue by knev** [omigroup/omigroup#107]
The translation of integrating two systems can be done directly in one of the two systems. Using IPSME translations can be made external to the systems being integrated offering the advantage of dynamic evolution. 
https://www.youtube.com/watch?v=WvoeUydcInA

This CfP is for individuals who are interested in integrating two systems via IPSME -OR- have two systems integrated, that wish to make the integration dynamic via IPSME. Integrations can be of arbitrary purpose: asset sharing, teleportation, social, stats, etc. Participants will create a dynamic translation component integrating two systems. The end goal is to make individual translations reusable by other members of the group, forming a greater whole i.e., a mini part of the Metaverse, if you will. Translations are not required to be open source and remain the property of each participant.

Participants in this CfP are individuals who have already integrated two different systems -OR- have knowledge of at least two APIs, of two different systems, that they wish to integrate. Each participant should have adequate knowledge on how to integrate the two chosen systems, but lack the knowledge on how to make those integrations dynamic via IPSME. Participants should want to work together with other members of the group to form a greater whole. Note, we shall not be forming standards for communication within this group.

Each participant will choose the two systems they would like to integrate and on which OS to do the integration. Web-only is considered a different OS similar to Chrome OS. Individuals who already have two systems integrated can join the group to make their integration dynamic via IPSME. Each participant must be able to code the integrations themselves; the point of the group to help with an evolutionary architecture via IPSME, not coding help.

The worst-case scenario is that: even if an individual finds IPSME obtuse, they have created a translation between two systems that is reusable, even without IPSME; the code is not lost.

**Comment by mrmetaverse** [comment]
Shared in discord channel for review. 

additional information: https://arxiv.org/abs/1806.05931

**Comment by mrmetaverse** [comment]
Team has reviewed a few times, will move to done to archive.
