### ISSUE TITLE
Metaversity - call for participation / collaboration 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#115]
# Metaversity 

## About

Metaversity is an open source project dedicated to helping people become new or improved metaverse creators. 

### Who we hope gets involved to make this happen? 

- A wide variety of people, with a wide range of Knowledge, Skills, Abilities, and Interests. 
- We hope multiple orgs are part of this creation, as multiple orgs have something like this on their backlogs and roadmaps, and the entire metaverse benefits when we increase the number of creators. 

## :bulb: Why are we here? 

>"I wanted to take all of my bookmarks that helped me become a webxr dev, and create a wiki that would help others" - Liam

We want to organically create value by helping others become Metaverse creators and contributors. We want to find creative ways to sustain ourselves. We want to create incentive structures that align with peoples values. 

People need something that keeps them focused, and moving forward on their mission to get involved with the Metaverse. It can be easy to run into a roadblock, and get deflated or distracted. We want to make achieving the goal of becoming or improving as a Metaverse creator more attainable. We want to create incentive structures that align with peoples values. 

Furthermore, we should strive to deliver this message with minimal fluff or bullshit. The goal should be to enable folks to discover solutions and make effective choices, using _inclusive language_. 

Eventually we will have more options for metaverse contributors. Beyond developers, there will be metaverse designers, metaverse modelers, and even metaverse entertainers. Shops, services, SaaS. 

>_The metaverse is the vehicle by which we all wake up to the game we are already playing._ - gheric

## :woman: Who are we serving? 

- People building the Metaverse 
- People who want to become Metaverse developers 
- People who want to create Metaverse products
- People who want to share their knowledge with others 
- We are indirectly helping other groups in the Metaverse seeking future hires, by effectively manufacturing metaverse talent. 

### Objective III: Launch first curriculums* 
KR: Craft 3 journey maps of people becoming metaverse creators
KR: Establish curriculum for each archetype.

**Comment by mrmetaverse** [comment]
Metaversity is a new initiative that we believe the entire metaverse ecosystem can benefit from. We believe this should be a collective effort, owned by no one group or company. It can be challenging getting started as a metaverse creator. We hope to create a system that helps people achieve their goal of becoming a creator. This could start as "how to become a webxr dev" or "3d modelling basics," and "getting started with solidity." Eventually, we hope this can provide an open resource for all sorts of metaverse creator paths. We hope brands and groups will contribute their own curriculum that helps people. Imagine a future "opening your metaverse store," and "making digital fashion," course. The sky is the limit, and we hope you will join this effort.

**Comment by yangwao** [comment]
I'm keen to help and contribute!

**Comment by onerawartist** [comment]
Im all in 😁

**Comment by mrmetaverse** [comment]
@yangwao @onerawartist invites sent to metaversity!

**Comment by soze316** [comment]
I'm late to this but yes, I'd like to be involved.

**Comment by FutureMeme** [comment]
It's on like Donkey Kong. I am in!

**Comment by mrmetaverse** [comment]
This has been moved to a new home: https://github.com/AngellXR/metaversity
