### ISSUE TITLE
XR Safety Week - Community Partnership

### ISSUE THREAD

**Issue by CyberGuardian-XRSI** [omigroup/omigroup#124]
#XRSW2021 Community partnership for Safety in the Metaverse  

Holidays are around the corner.. so is XR Safety Week 🥳🥳🥳

The XR Safety Week is an annual event powered by XRSI. It is both a celebration of the many different facets of XR and an opportunity for individuals, organizations, policymakers, and institutions to promote ideas that will guide us towards a safer future with XR technologies.
Getting into XR might seem as straightforward as putting on an HMD or holding up a phone to view Augmented Reality (AR) content. However, cultivating a sense of safety is imperative.
This week encourages everyone to get into XR with awareness, independent of the use case platform or experience.

Celebrate with us: www.xrsafetyweek.org
 
Why XR Safety Week?
By dedicating these five days events around various themes, XRSI intends to create a reflection point on the safety and trust aspects of immersive technologies and XR ecosystems, aka the Metaverse. This is necessary to address the need for technological risks this holiday season due to the expected increase in purchasing the latest XR devices, platforms, experiences, and games.

Also, Apply to take part in the XR Data Classification Roundtable during XR Safety week: https://dc.xrsi.org/
 
The foundation of the XR Safety Week is “safety” for the simple reason safety is of critical importance when exploring unique innovations of XR to remain mindful of the implications that come with those concepts. Each year before the holidays, XRSI will promote this time of the year to ensure that we engage with XR technology with safety at the forefront.

**Comment by mrmetaverse** [comment]
Thank you for bringing this to our attention. We will be sure to add this to our Wednesday sync! :)

**Comment by mrmetaverse** [comment]
Evo: This is the 2nd week of December, so we have a little bit of time if we want to put something together. Let's think about the significance of identity. Evo suggested this may be a great opp to collaborative with the internet identity workshop (IIW). 

would love if next week we can come with to the table with ideas, and content and messaging to spread the word  or get involved.

**Comment by mrmetaverse** [comment]
Proposed tying our twitter spaces chat about mapping to the importance of XR Safety and inclusion. Discussed becoming a supporter or sponsor of XR Safety week, potentially making this week XR Safety specific to help spread the word of XRSI, XR Safety week, and how it ties in with our work.

**Comment by CyberGuardian-XRSI** [comment]
Please review the community partnership deck and send ur logo to matt@xrsi.org cc marco@xrsi.org, should u decide to become the community partner

[XRSW Community Partnership Deck.pdf](https://github.com/omigroup/omigroup/files/7611027/XRSW.Community.Partnership.Deck.pdf)

**Comment by CyberGuardian-XRSI** [comment]
To become a sponsor , select a tier and email us with payment details etc. via marco@xrsi.org and matt@xrsi.org
[XRSW Sponsorship Deck 20211122 web.pdf](https://github.com/omigroup/omigroup/files/7611029/XRSW.Sponsorship.Deck.20211122.web.pdf)

**Comment by LightLodges** [comment]
Let me know if you did not get the donation and payment from last month
Kavya and I'll see you at any events where you need an extra hand this week.

-evo

**Comment by John-Nagle** [comment]
Does "safety" in this context mean not falling on your face due to VR disorientation, or not being exposed to content you don't like?

**Comment by CyberGuardian-XRSI** [comment]
I explain the context in the podcast ( link in the tweet) https://twitter.com/xrsidotorg/status/1467365930611085313?s=21

**Comment by CyberGuardian-XRSI** [comment]
Hi there!

I explain the context in this podcast: https://twitter.com/xrsidotorg/status/1467365930611085313?s=21



Best,
Kavya

**Comment by John-Nagle** [comment]
Issues in Github should be explained in Github.

**Comment by CyberGuardian-XRSI** [comment]
What grade is this? High school .. with all due respect, I provided a detailed explanation in an audio recording .. I would appreciate if you respect my time and advise you don’t demand a redundant explanation unless my recorded explanation doesn’t satisfy your intentions to learn more about “Safety” in XR

**Comment by mrmetaverse** [comment]
Closing this as it has already passed. Furthermore, we do not speak to each other this way. GitHub is our knowledge base.
