### ISSUE TITLE
next week we can come with to the table with ideas, and content and messaging 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#126]
Evo: This is the 2nd week of December, so we have a little bit of time if we want to put something together. Let's think about the significance of identity. Evo suggested this may be a great opp to collaborative with the internet identity workshop (IIW). 

would love if next week we can come with to the table with ideas, and content and messaging to spread the word  or get involved.

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/issues/124#issuecomment-971790329_

**Comment by John-Nagle** [comment]
Some basic identity issues for discussion:

- Can you have as many identities as you want? Or is there a "real names" requirement, like Facebook?
- Do identities own stuff? If so, where are those assets kept?
- What information about an identity is public?
- If you cross from one metaverse to another, do you retain the same identity?
- Can you retain an identity even if the metaverse where you created it bans you?

**Comment by mrmetaverse** [comment]
Closing due to this being in the past
