### ISSUE TITLE
Community sustainability with pet3rpan

### ISSUE THREAD

**Issue by madjin** [omigroup/omigroup#128]
pet3rpan is a guru of community building and DAOs, some reading for those unfamiliar:

- https://www.pet3rpan.net/blog
- https://medium.com/1kxnetwork/how-to-grow-decentralized-communities-1bf1044924f8
- http://mission.metacartel.org/

Lately I noticed he has been joining metaverse interoperability channels like OMI, M3, WebXR hackathon channel.

One model for sustainability is:
1. Launch a grants DAO focused on funding projects, experiments, research (and grow a thriving community of builders)
2. From the community built with the grants DAO, create an community owned that invests in the projects incubated by builders. On top of this could run events, raise sponsorship funding etc.

This was the path MetaCartel mostly took (community for web3 dapp devs started in 2018 when there was barely any funding available)

I want to setup a time for a brainstorming session and discussion around this, post below if interested and when works for you.

**Comment by pet3r-pan** [comment]
I am here to help! Let's do this.

**Comment by mrmetaverse** [comment]
you know I am interested, have been working on putting together a grant DAO for a couple of months. Would prefer to collab!

**Comment by mrmetaverse** [comment]
Bump. 

- MAD (Metaverse Alliance DAO) is starting to stir again, so we could see something juicy in the Grants space. 
- Jin has been making efforts like Danknugz for raising funds for metaverse grants 
- AngellXR is going to announce our efforts to raise a fund for our incubator and online accelerator in the next few weeks ❗ (finally)

**Comment by madjin** [comment]
Yo yo! Last week launched fundraising for open source metaverse grant funding program via 3D crypto weed lol.
Here's the announcement post on dank nugz: https://twitter.com/dankvr/status/1516866869348732935
Story behind it on: https://m3org.com/nugz/

So far $5k raised 🥳  Working on a blog post and a secret project for making the most out of every grant announcement 😉

**Comment by mrmetaverse** [comment]
closed during refinement today
