### ISSUE TITLE
Suggestion: Adopt a Feedback channel on github

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#129]
I think we should consider creating a new repo, omigroup/feedback. The purpose of this repo would be solely for making suggestions, giving feedback, and discussing integration blockers/needs/successes. Github actually has their own [github/feedback](https://github.com/github/feedback) repo, which can be searched, tagged, etc. 

We already leverage the holistic backlog, which lets us syndicate tickets from all of our active repos. This means, we could have a feedback channel, and the group can select to pull in, or defer, items of feedback into our holistic backlog. Effectively "activating" that piece of work. 

I think this could help newcomers find answers to common questions, and provide a new inlet for the most important element of iteration - feedback! 

The repo would look like [this](https://github.com/github/feedback/discussions): 

[![image](https://user-images.githubusercontent.com/63426722/142430678-0cb210a3-7e00-4bf6-80c5-f87b2daf6aa5.png)](https://github.com/github/feedback/discussions)

**Comment by mrmetaverse** [comment]
Jin suggested just using a meta tag in issues (like we are currently doing) 

![image](https://user-images.githubusercontent.com/63426722/145254230-4daf7e78-ba1a-47b9-bf08-5e5b98287614.png)

**Comment by mrmetaverse** [comment]
Keeping this open for discussion. May not be necessary

**Comment by robertlong** [comment]
I think we can add a section to the README that just details how to give feedback. We should also add this section to our CODE_OF_CONDUCT document and about channel on discord. I think we should ensure that there is a private feedback channel as well. We can give out the OMI admin email for that if it helps, otherwise people can always DM us on Discord.

**Comment by mrmetaverse** [comment]
Deprioritizing due to existing methods of managing feedback being satisfactory.
