### ISSUE TITLE
Open metaverse community calendar

### ISSUE THREAD

**Issue by madjin** [omigroup/omigroup#130]
The open metaverse is decentralized across many discords and communities, lets have a calendar system for the cool events happening in between. To start with:

- OMI
  - weekly community call + gltf working group
- M3
  - Friday twitter spaces
- VRChat (for the culture)
  - https://vrchatevents.com/

> Maybe the real metaverse are the friends we made along the way

**Comment by madjin** [comment]
RedEagle_P1 runs a group dedicated to making sure that the future of the Metaverse is of-for-and-by the people and wants to partner up with anyone interested in that. They do a weekly event in which we discuss the metaverse and enter one (like Alt Space VR) together on Sunday at 1pm EST. 

- Anyone from high-level professionals to total newcomers are welcome
- Focus on expanding the space
- Next week will have a Microsoft exec working on Minecraft joining

Events are listed here: https://discord.gg/QaNH9ukWnm with the top one being related to the Metaverse

**Comment by madjin** [comment]
Calendar topics are opt-in btw! I think it'd be super useful if open metaverse community had a shared calendar event system so that we can coordinate more effectively together. RedEagle_P1 has a good discord bot. I like the calendar on vrchatevents.com. Discords event system is pretty good too. Events are the heartbeat of communities.

**Comment by RedEagleP1** [comment]
We have a bot to do this within Discord we are willing to share with you guys. We might even open source it. Another option is making a relevant Reddit and using that. Finally someone can custom-code a solution that is web based. What's the best option here?

**Comment by madjin** [comment]
As a first test case we can setup an OMI event that links to the event page for RedEagle_P1's event
I'll setup events in M3 discord
I'm down to try stuff and document what we learn along the way

**Comment by mrmetaverse** [comment]
+++ I think that's a great idea. And love the idea of documenting what we learn along the way.

**Comment by mrmetaverse** [comment]
We have this one for now: 
https://calendar.google.com/calendar/u/1?cid=Y18wZHB1Z2Y5ZjgzZXE0cWVrbWI2b21xYmptZ0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by mrmetaverse** [comment]
VRChat events discord has a great opt-in alert exemplar

**Comment by mrmetaverse** [comment]
RedEagleP1 offered to connect us with the person who maintains the bot they are using

**Comment by mrmetaverse** [comment]
We need a partner to help see through the execution of a shared event calendar on our website. 

We already have a OMI event calendar here: https://calendar.google.com/calendar/u/1?cid=Y18wZHB1Z2Y5ZjgzZXE0cWVrbWI2b21xYmptZ0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t
