### ISSUE TITLE
WASM UGC Scripting Working Group

### ISSUE THREAD

**Issue by robertlong** [omigroup/omigroup#133]
# WASM UGC Scripting Working Group (Final name TBD)

Back in September I started a [GitHub discussion](https://github.com/thirdroom/thirdroom/discussions/15) in the Third Room repository for a Web Assembly Entity Component System API that could be used for sandboxing scripts. I think that there may be enough people interested in this idea at OMI that it may warrant a working group for designing it.

I'd like to propose starting a working group for the development of standard WASM APIs for performant sandboxing of user generated content scripts. This API would be designed to run in any compatible WASM runtime and would not be constrained to the web.

Implementations will likely be platform specific. There also will likely be vendor specific APIs as we propose new additions. This group would not cover implementation, however parties are encouraged to work together on common implementations for various engines.

**Comment by AdamFrisby** [comment]
We implemented this in Sinespace internally a few months ago - not quite available, but I am *definitely* interested in this topic.

**Comment by mrmetaverse** [comment]
Lively discussion during todays discussion #139 
Multiple attendees expressed interest. 
![image](https://user-images.githubusercontent.com/63426722/145258956-e616cf23-0cd2-4a44-9f2a-45dbaa491210.png)

Take it to a vote?

**Comment by mrmetaverse** [comment]
Possibly not starting until January. Want to ensure we have the support we need to manage this groups workflow.

**Comment by mrmetaverse** [comment]
Adam at very least volunteered

**Comment by mrmetaverse** [comment]
Form newly approved WASM working group.

**Comment by mrmetaverse** [comment]
Vote Passed: ![image](https://user-images.githubusercontent.com/63426722/145259899-f3443bd0-0488-48af-95b2-ed6de78fcfeb.png)

**Comment by robertlong** [comment]
If people who are interested could chime in here with what you are interested in this space, that'd be great! I'll find a date and get the Discord role set up.

**Comment by lyuma** [comment]
I love the long term vision. My interests are in splitting this up and solving some of the interesting sub-problems. I'm interested especially in resolving some of the low level interface / ABI issues related to WASI and non-web platforms, and enabling more languages to compile in a framework-agnostic way.

While C and C++ are easy to compile, many languages, including C# and Lua, are difficult to compile without dependencies on arbitrary browser APIs.

**Comment by cdata** [comment]
An ubiquitous portable, sandboxed runtime environment for interactive content seems inevitable. My main uncertainty is whether we can agree on the shape of such an environment as a community, or if one ends up being thrust upon us unilaterally from <pick your source>.

WASM gives us a convenient substrate for experimentation and discovery of a plausible standard. I'm interested in investigating its strengths and weaknesses - and the opportunities it presents - with this group.

I've worked a bit on the problem of sandboxed/portable scripting for interactive 3D objects while building https://github.com/google/model-viewer. My perspective is that of a web browser engineer with game dev experience. I'm also very interested to hear the perspectives of others who are more oriented around game engines such as Unity, Unreal and Godot.

**Comment by AdamFrisby** [comment]
> I love the long term vision. My interests are in splitting this up and solving some of the interesting sub-problems. I'm interested especially in resolving some of the low level interface / ABI issues related to WASI and non-web platforms, and enabling more languages to compile in a framework-agnostic way.
> 
> While C and C++ are easy to compile, many languages, including C# and Lua, are difficult to compile without dependencies on arbitrary browser APIs.

I agree - they're extremely painful. There's some _very_ hacky ways of getting C# in via NativeAOT builds; and would love to work on exploring how to make those easier.

The biggest problem in my view is the ABIs, and memory management - even passing a simple string into and out of WASM is a godawful experience for a platform/toolchain developer.

That said, it's the best option out there - alternatives don't have the possibility of multiple language support, or carry larger security risks. Embedding things like the .NET Runtime, while nice in theory, is painful in practice in a cross-platform environment; WASM is at least _possible_.

Nonetheless, I am happy to champion Unity support. 

I have also implemented multiple SDKs for Virtual Worlds including their API sets in the past.

I would suggest at this early stage, a working group frequency of every two weeks would be ideal - if we can push it in prior to the normal OMI call, that would be lovely, although I know that might be early for some folks.
