### ISSUE TITLE
Metaverse Association non profit planning 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#134]
# Metaverse Association - A new non profit grant source for the open metaverse 

**We would like the help of the OMI community to ensure the github and discord are conducive of a collaborative environment.** 

Press release slated for tomorrow Dec 2nd, 2021: 

The Metaverse Association is establishing a non-profit foundation to support those who are building the open and interoperable Metaverse. The fund aims to bring together both traditional and crypto native capital to support critical infrastructure and open source initiatives. We believe the entire ecosystem benefits from these efforts and we aim to accelerate its development by removing capital as a constraint.

Important inflection points in enabling technology and public belief have set the stage for the Metaverse to emerge after many prior attempts by industry pioneers. In order for this initiative to be a success it requires broad collaboration and access to opportunity. While we recognise that blockchain has the potential to be an important component of the Metaverse, it must be emphasised that it is not the entire solution. DAOs are an innovative structure, but these funding sources can exclude non-crypto-native participations, which is a barrier to achieving a well balanced metaverse.

We strive to be a diverse collective immediately. Our efforts must be collaborative and representative of all who contribute to, or are affected by our work together. Therefore, the Metaverse Association’s structure and governance should be shaped collectively by our community, rather than crafted from a single perspective.

We ask for all those who share this vision, to unite in working together. Please join us on Github and Discord, and help make the Metaverse open, and interoperable for all.

**Comment by AdamFrisby** [comment]
I can see some emphasis on Blockchain/etc in the description and some language disclaiming that - how independent is this from that? We're interested in interoperability and open standards, but we are not interested in blockchain based standards/technologies.

What is the scope for the association as well - what activities does it anticipate doing specifically?

**Comment by lyuma** [comment]
^ I think the majority of the text in the explanation is talking about what the Metaverse Foundation is not, so it's a bit confusing if you just quickly skim the text.

I think I understand that it is there to explain *why* the Metaverse Foundation is not a DAO or other blockchain based distributed entity. But it distracts from the point of this foundation. Maybe it can be reworded / made more concise?
