### ISSUE TITLE
OMI-Chan Avatar effort

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#135]
Nova has been working on the omi-chan avatar effort, and would like to ask that others get involved with the creation/design. Especially to ensure that OMI-chan can represent a diverse group and not the thoughts of just one person. 

OMI-Chan Avatar effort

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/132#discussioncomment-1729931_

**Comment by mrmetaverse** [comment]
What efforts should one person be able to contribute, versus what types of decisions should be made by a group?

**Comment by mrmetaverse** [comment]
prop: forming a working group. Discuss here, and next week we can vote on forming a working group.

**Comment by technobaboo** [comment]
please i really want to get a working group started, link the process to that?

**Comment by mrmetaverse** [comment]
What will this working group work on? What is the overall objective or expected outcomes? cc: @technobaboo 

Reference this ticket in a new cfp proposal issue, and we can vote again next week :D
