### ISSUE TITLE
OMI-chan Avatar/Mascot Working Group

### ISSUE THREAD

**Issue by technobaboo** [omigroup/omigroup#137]
# OMI-chan working group

The purpose of this group would be to discuss the design for a mascot of OMI, as well as figure out the funding in order to pay artists to make it into an avatar. The avatar would be for several purposes:

- To provide a personification of OMI that makes our collective stance easier to understand
- To use as a vtuber for videos about OMI explaining concepts and representing the group
- To allow other people embodying the avatar to promote OMI
- To test different platforms' avatar interoperability

The design has been partially completed, but is still subject to change and given I've been the main one deciding the design while OMI-chan is supposed to represent the group, I need to make sure others are a part of the decision making process.

Formal working group proposal of #135

**Comment by jsejms** [comment]
@technobaboo Hey, I'm a UX/UI/Product Designer and I'd definitely be interested in helping with this working group.

**Comment by mrmetaverse** [comment]
The mascot is the primary effort. The use of the mascot for things like testing interoperability is an applied bonus. For example in VRChat Unity-chan was a very popular avatar choice.

**Comment by robertlong** [comment]
We'd like the final vote for final avatar approval to happen during the weekly working group meetings, but this group can operate autonomously to get to that final design. I'd recommend check-ins with the larger group when there is work to share.

**Comment by mrmetaverse** [comment]
Motion approved to form the OMI-Chan group @technobaboo

**Comment by robertlong** [comment]
For:
![image](https://user-images.githubusercontent.com/1753624/145253796-57e07cec-e594-4d44-87df-b4ca6f40df60.png)

Abstentions:
![image](https://user-images.githubusercontent.com/1753624/145253862-e2e5efab-01e7-4e07-8694-b210c1b454af.png)

Against (none, Jesse started the vote):
![image](https://user-images.githubusercontent.com/1753624/145253920-54bca021-0148-4d48-a622-94454ca5ee63.png)
