### ISSUE TITLE
Form the approved Partner Program exploration group

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#143]
This group needs a group to meet separately from our Wednesday sessions. 

Who can lead this effort and organize the exploration of what a partner program may look like?

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/issues/121#issuecomment-989020315_

**Comment by RedEagleP1** [comment]
I am interested.

**Comment by Toasterson** [comment]
Me too

**Comment by fire** [comment]
Is approved Partner Program exploration group inactive?

**Comment by mrmetaverse** [comment]
Doesn't appear to be active _yet_ but could be instated if a lead steps up and wants to set a initial date, and set up the repo. I can help with getting the repo going. I am moving this ticket to blocked.

**Comment by mrmetaverse** [comment]
This is the Interoperators Group. The goal is to meet this Friday 2/25/22 at 17:00 UTC (9am PT) 
:calendar: add this event to your calendar [using google cal](https://calendar.google.com/event?action=TEMPLATE&tmeid=NzNla2d1MDZzNnYybWNhZDZsN3ZxaDdyYWNfMjAyMjAyMjVUMTcwMDAwWiBjXzBkcHVnZjlmODNlcTRxZWttYjZvbXFiam1nQGc&tmsrc=c_0dpugf9f83eq4qekmb6omqbjmg%40group.calendar.google.com&scp=ALL)
