### ISSUE TITLE
Form the approved OMI-Chan working group

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#144]
Motion approved to form the OMI-Chan group @technobaboo

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/issues/137#issuecomment-989012855_

Who will lead? When will you meet? Create a repo.

**Comment by technobaboo** [comment]
Should I be the leader? Trying to start up the current OMI-chan efforts as well as the Constellation efforts has been very challenging for me and I don't know if I'd be a good candidate :S

**Comment by fire** [comment]
@mrmetaverse Can you assist with the creation of the working group machinery for our meeting tomorrow?

**Comment by mrmetaverse** [comment]
@fire I have set up the readme with the basic info you will want to decide on in today's meeting. Just edit the readme and push to master. 

![image](https://user-images.githubusercontent.com/63426722/151669431-ac805088-91cb-4a3e-a6d6-53e05a4ee94f.png)

I have also set up discussions and the omi-chan backlog.
