### ISSUE TITLE
Metaverse business collaboration

### ISSUE THREAD

**Issue by RedEagleP1** [omigroup/omigroup#150]
**Metaverse business collaboration group**

The purpose of this group would be to help people find and maintain work in the *ethical* part of the metaverse space in order to make sure we can invest our time fully to have maximum impact. 

It's also for business leaders to network with other business leaders in the space and find ways that we can collaborate. 

We need: 

Participants
A meeting organization leader
Topics we should discuss. 

I would really like to emphasize that even though I think we're all believers in the idea that different ideas should be tried in this space, I really want to avoid anything that doesn't have a lasting positive impact on the consumer of the metaverse. No get-rich-quick schemes. No taking advantage of people who know very little about the space.

**Comment by Toasterson** [comment]
As one of the members of a group that tries to Achive this kind of Business, I would definetly be keen to join.

**Comment by nathangrotticelli** [comment]
Would 💯 be keen to join/lend my participation as well

**Comment by mrmetaverse** [comment]
In the past we have believed that multiple orgs should lead the way here, and not federated inside of OMI. Groups like AngellXR are also groups that collaborate for metaverse business collaboration, but aren't the only ones. The more the merrier! We want to be careful to ensure that OMI doesn't become a group creating businesses itself. 

From todays meeting RedEagle called out making this like a support group for open metaverse corps to come together and collaborate and help each other talk through issues / challenges in the metaverse.

LOVE this idea for a support group

**Comment by RedEagleP1** [comment]
> 

Thanks for the reply, I feel like it would be great to facilitate those conversations but not actually do any projects as OMI. Do you feel that is appropriate here?

**Comment by nathangrotticelli** [comment]
> > 
> 
> Thanks for the reply, I feel like it would be great to facilitate those conversations but not actually do any projects as OMI. Do you feel that is appropriate here?

+1

**Comment by mrmetaverse** [comment]
We discussed this in meeting, and continue to circle around this topic as a group. moving to done for now, but will ref later as we continue discussing other topics like the Angell Incubator, etc.
