### ISSUE TITLE
OMI Matrix Bridge

### ISSUE THREAD

**Issue by robertlong** [omigroup/omigroup#152]
I'd like to propose that we create a Discord channel that is bridged to Matrix. @thibaultamartin, my co-worker at Element has volunteered to set things up and I already have a matrix room #omi:matrix.org that we can use for this. The goal would be to have this channel as a method of discovery for people on Matrix but not on Discord, as well as a prime example of interoperability for us to dogfood.

What do you all think?

**Comment by Toasterson** [comment]
Since I am using Matrix for all my other OpenSource Chat incl. IRC, I love the Idea. I joined the existing channels!

**Comment by mrmetaverse** [comment]
ABSOLUTELY! We tried and failed at this before OMI even got started 😅 I know other members of our OMI group _have_ succeeded before too. I motion to take a vote on Wednesday (if needed). 

Point of order: Robert works for Matrix. I do not see any conflict of interest with this effort. If you do, please share why, and the alternative.

**Comment by mrmetaverse** [comment]
@robertlong We actually reserved #OMI:matrix.org as well several months ago. Does capitalization matter? Like are we talking about the same space or are they separate? 

![PXL_20211224_143548264.jpg](https://user-images.githubusercontent.com/63426722/147359518-d78cf136-f68d-467d-9935-44078d506188.jpg)

**Comment by robertlong** [comment]
Wow, yeah seems like capitalization matters. I do have the lowercase one.

**Comment by mrmetaverse** [comment]
@robertlong ok let's use yours and we can archive the one I reserved ☺️

**Comment by mrmetaverse** [comment]
Bump 😶‍🌫️😁

**Comment by thibaultamartin** [comment]
If it help, there's a video explaining how to set-up a free Discord bridge: https://www.youtube.com/watch?v=5xLqQvt3aig

**Comment by mrmetaverse** [comment]
I almost want to do it simply for the experiment. It only syncs with one channel right? Like we would make a bridge channel in discord and/or matrix? Or can we replicate all primary channels and link general to general, gLTF group to gLTF group, UX Research channel to UX Research channel, etc.

**Comment by mrmetaverse** [comment]
no interest
