### ISSUE TITLE
Proposed having a Hackathon Planning group or participating in others!

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#173]
Posted on behalf of Evo: Members of the community would like to see OMI host/co-host a hackathon for March or April. 

We need support planning, and to decide on a date, preferably during the weekend between March and April. 
- could we coordinate with anyone hosting the webxr hackathon?

**Comment by mrmetaverse** [comment]
Quoting Evo: 

"We should start reviewing our event strategy and the ways that people can get involved at all levels. 

- hackathons
- in person events 
- etc. 

When should this happen, and what are the primary goals of that experience?"

**Comment by mrmetaverse** [comment]
Jin Suggestion: Consider partnering with Zesty, M3, Metafactory, etc.

**Comment by mrmetaverse** [comment]
"April is a realistic timeframe"

**Comment by mrmetaverse** [comment]
"Fireside chats, interviews, etc. 

We should have events to create things together. Maybe intros and outros, custom avatars, etc."

Also a good chance for the OMI-Chan effort to collab,.

**Comment by mrmetaverse** [comment]
Jin has an area/space in mind

**Comment by mrmetaverse** [comment]
Topics: 
- Avatar portability 
  - invite people using VROID to use their avatar on other platforms than VRChat. 
- meta-traversal 
- collabs with artists to bridge build between sectors 
- inventory and assets

**Comment by KooIaIa** [comment]
I really don't like hackathons being in a community like this - but they are fine being separate. We are hard pressed enough to devote energy to our own working groups. Hackathons are a great way for interest groups to manipulate communities to use their technology for prizes. But we don't need to be judged or artificial incentives here. Interoperability for the sake of interoperability is very different than incentivized interoperability.

**Comment by mrmetaverse** [comment]
> I really don't like hackathons being in a community like this - but they are fine being separate. We are hard pressed enough to devote energy to our own working groups. Hackathons are a great way for interest groups to manipulate communities to use their technology for prizes. But we don't need to be judged or artificial incentives here. Interoperability for the sake of interoperability is very different than incentivized interoperability.

Yeah I agree. I think hackathons are a great thing that can benefit the open metaverse, but don't know if we have the capacity at OMI, and it also treads a dangerous line of "well we have the hackathon, now we need to raise funds to fund winners, etc." OMI was created to focus on co-creating protocols. "Interoperability for the sake of interoperability is very different than incentivized interoperability," I resonate with this especially. 

Now one thing I will add, Angell (and other groups in OMI) is outfitted to run hackathons, and incubate products/projects/communities. We are happy to co-host events like hackathons, and will eventually become a proper incubator/accelerator for open metaverse projects. But Angell is a separate org, and is capable of supporting this stuff. I want to make it clear that Angell can help with this, but that we would encourage others to get involved as well, as this is not Angell show. We are all part of this together. So... if we want to think about OMI getting involved with hackathons, we should actually look at partnering with other orgs to do so. OMI resources are already fairly constrained, and we operate on virtually no budget.

**Comment by mrmetaverse** [comment]
> 

It really sounds like we need a proper event planning group, that meets regularly, with its own github backlog. These ad-hoc issues often feel out of place here in the main omigroup repo. If events is something we want to do, we need to give it the respect it deserves. A repo with a readme following our best practices (how to get involved, what the group does, when they meet, etc.), a backlog with in-flight and potential opportunities (cause it feels like we have new idea every 2 weeks, and rarely follow through), and better accountability overall. Planned sessions, regular meetings, and opening up involvement to the entire community. 

without this, I don't see many of these events we propose actually happening without drastically redirecting OMI resources. Create the group, have some structure, and see who shows up to make it happen. If nobody shows, then it is not an OMI priority.

**Comment by mrmetaverse** [comment]
From grooming: 

"Hackathons, game jams, un-conferences are all being organized by other groups, how about we partner with them rather than organizing our own?"
