### ISSUE TITLE
Call for Nominations for 2/2/22 Election

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#174]
The next OMI election is set for 2/2/22 during our next weekly meeting (17:00 UTC). 

notes: 

- We are not locked in, if we need to make changes to the OMI structure during the next term to the overall OMI structure, we can and will. We should not brush this conversation under the rug until next election. 
- Tracking all of this in this Milestone: https://github.com/omigroup/omigroup/milestone/2
- The new structure of OMI proposed discussion: https://github.com/omigroup/omigroup/discussions/157
- OMI responsibilities Audit: https://hackmd.io/@mrmetaverse/omi-tasks-audit 
- Potential New Roles as a result of the responsibilities audit: https://github.com/omigroup/omigroup/discussions/165 
- Review our **core values**, as they help define our structure: 
  - We collaborate, driven by research, privacy and accessibility, to make the metaverse more human.
  - We work incrementally, iteratively, and with intent.
  - We are creating a cooperative, sustainable culture of innovation.
  - We empower the people making the metaverse.
  - We must cultivate resiliency by championing diversity, and freedom of choice.

Please post your nominations in this thread below :point_down:

**Comment by fire** [comment]
Need to update w3c charter since we are expected finished specifications.

**Comment by mrmetaverse** [comment]
> Need to update w3c charter since we are expected finished specifications.

Agreed. We need to revisit our charter and structure overall. A goal of mine is to craft and adopt a new structure by July 1st, 2022 or earlier.

**Comment by RedEagleP1** [comment]
Wishing you all the best for this!

**Comment by mrmetaverse** [comment]
X-post from agenda comments for 02/02/22: 

Today we can vote to extend the existing terms by 90 days and commit to continuing to discover our new structure, or we can have the election as scheduled and commit to a new structure within 90 days. I defer to the group to make this decision with two votes if needed: 

Vote 1: Vote to extend existing chairs by 90 days 
Vote 2 (if vote 1 fails): Have the election as usual. 

I don't see any nominations so I assume the group wants the same chairs but we are all committed to dividing our responsibilities and creating new roles. I know I'm not alone when I say I want to do the right thing and find the best structure for all rather than just going through the motions. 

I will be on mountain today and may have shoddy service. I am honored to have served and to have a group like you to meet with, and would be honored to continue serving as chair. But, I will be committed to finding the right structure in the next 90 days.

**Comment by fire** [comment]
Vote 1: Vote to extend existing chairs by 90 days.

**Comment by fire** [comment]
I also nominate @mrmetaverse for being a chair.
