### ISSUE TITLE
Joint events proposal

### ISSUE THREAD

**Issue by RedEagleP1** [omigroup/omigroup#187]
OCEM does a big weekly event in which we discuss the Metaverse, answer questions etc.
We are trying to create value without necessarily asking anything in return. I'd love to share the burden and the reward -- namely, we could all meet together, help each other lead and have that event in multiple discords within this space to get multiple points of view. 

I would like to propose making the big weekly meeting OCEM does something we do sometimes in OMI, sometimes in M3 etc. I feel like we can provide more value for more people while spreading the audience etc. 

Bringing the greater community together for events could be a great way for us to impact the Metaverse space with the ideas of the OPEN Metaverse. 

I would love to propose this during next Wednesday's meeting. Sadly, we have a meeting at the same time so I was wondering if we could extend by 20 min and we will all pop in from OCEM and chat with OMI?

**Comment by mrmetaverse** [comment]
Hey Red! Love the idea of collaboration. The group would probably need more details, such as what you'd like this "event/talk" to look like. 

Next week we are meeting for 2 hours to discuss meta-OMI structure, so bring this back up for the following weeks agenda (week of 3/23). Regarding staying late, I am not sure if we can get many to stay later, could you all cut your meeting short and consider talking in our group as part of your meeting agenda? Not sure why we would _have_ to stay late, but you're welcome to try it that way too. Often a few people hang back in the end. 

It may be best to have a specific event planned, as having your meeting "in other groups" might not be specific enough for folks to have a discussion about. 

Lastly, it's always possible that people aren't interested. If that happens, don't take it personally, everyone is giving what they can when they can and most people are pretty stretched these days. I've found the group responds best to details. 

Regarding process: after discussing during a weekly meeting, this ticket will be moved to done.
