### ISSUE TITLE
First Interoperator Meeting Friday 2/25/22

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#188]

**Comment by mrmetaverse** [comment]
https://github.com/omigroup/omigroup/issues/121#issuecomment-989020315

**Comment by LightLodges** [comment]
# INTEROPERATOR MEETING
2/25/2022
- [this group formed by vote](https://github.com/omigroup/omigroup/issues/121#issuecomment-989020315) to explore what a affiliates or "friends of OMI" program or system could look like. 

## Engagement Strategy
*** Working groups - existing groups
*** Skunkworks - separate group from org with a mandate to get things done, merges back with main org, contributes to the whole of the field & community

* Social Field Trips

* Other Activities


## Interoperator 
W3C - technical partner
OpenCollective - fiscal sponsor

Forming partnerships/relationships with:
* XRGuild - nonprofit association
* XRCollaboration - metamapping, metatraversal events
* AngellXR - long term incubation/acceleration support 
* 

In collaboration with
IEEE working groups: "collaborators"
W3C working groups:  "collaborators"
Fieldbuilding associations:  ?
Metaverse businesses:   ?  "partners"


Short term sponsorships also possible?
Do we want to require a set of donations or sponsorship options to support OMI as a company?

Companies can support OMI through donations of TIME, TALENT, RESOURCES - MONETARY OR TECHNOLOGY

Nonprofits can support OMI and build relationships through community events, participation in working groups, mutual invites to conferences and building educational and scholarship programs for open source development.




# INQUIRY questions:
Do we want/need contributions for viability of our work long term?

Is there an expected donation for corporate or other organizational partners?

Is partnership = a contribution of money or technology or effort? 

Do we want to accept and work with short term sponsorships of specific events and experiences?

How do we engage in and help grow consortiums on collaborative endeavors?

What is allowed, what is not allowed, what is forbidden?  A conversation to open up with everyone - what is the expectation?  - March, post-strategy meeting add to agenda

Conflict around OMI getting big -- if we are successful do we get funding to do more, and do we become a big beast in this process?  We are not currently set up to become a behemoth organization


Where we feel safe & comfortable:
Being an open source community
Doing social events
Participating in working groups
Coming together regularly
Twitter spaces & community conversations
Building relationships through public dialogue
We work on spec toward standards for an open interoperable metaverse
We gather for research & development


Where we feel uncomfortable/edges:
Spec process - edge of anonymity/participation
Hackathons - do we want to do this?
Org confusion/language clarity & expressions 
Do we accept funding?
What do partnership expectations look like? Quid pro quo?
Uncertainty of growth - how can we provide space for generative R&D amidst the discomfort?
Edges block us - transparency helps - 
Moving OMI Discord to Matrix?

What we feel is too risky:
Becoming too big
Taking too much money tied to larger expectations
Vulnerabilities - hacking

March 11th Friday - timing TBD
Next steps:
What problems to solve: language
Clarity of goals and relationships
Identify tools and strategies to share
Engage community to participate in the R&D process
Talk through edges to make decisions on who we want to be, where to focus energy
Output of results of conversations - how do we share, record?
100 current ways to participate and play
Signal boosting together - streaming teams
