### ISSUE TITLE
:bug: streaming on twitch and YouTube still says "interopability demo night"

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#195]
:bug: streaming on twitch and YouTube still says "interopability demo night" 

![Screenshot_20220309-120453.png](https://user-images.githubusercontent.com/63426722/157493194-b22a5a02-e553-4126-9864-57ceec34ce44.png)

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/194#discussioncomment-2325695_

Suggested solution: Change stream title to "Join the Open Metaverse Group Live"

**Comment by mrmetaverse** [comment]
bump. Shared again today with the other chairs.

**Comment by LightLodges** [comment]
addressing this now in our Twitch to stop the bot

**Comment by mrmetaverse** [comment]
Update Twitch background
