### ISSUE TITLE
Confirm or fix the OMI calendars timezone

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#202]
There was chatter yesterday about mixed times on the [OMI calendar](https://calendar.google.com/calendar/u/0/embed?src=c_0dpugf9f83eq4qekmb6omqbjmg@group.calendar.google.com). I don't exactly understand what is broken, but want someone to confirm that the calendar is correct, and if needed, fix the time zone to adjust for daylight savings. I also tried to adjust the times on[ the github readme](https://github.com/omigroup/omigroup) to adjust for daylight savings, but may have gotten something wrong. 

Definition of Done: The OMI Calendar accurately reflects which time we will be meeting for our working group events, AND the github omigroup/omigroup readme accurately reflects the right times.

**Comment by robertlong** [comment]
We discussed this in our meeting today. Each working group can choose the timezone they use for their own group and on the calendar event. I think we need to double check that the timezones in Readmes/Discussions match the timezones of the calendar event. Our general meeting will stay at its UTC time and we'll ask in the other working groups for leaders to double check their own events.

**Comment by fire** [comment]
Avatar group is good as is. I'm not sure if this is a difference. This may mean the calendar does not match the meeting time?
