### ISSUE TITLE
Proposed social media automation and content strategy group. 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#205]
Social media: Automation our twitter and pre-plan our content . This suggests a content-strategy working group. This would assign the social media under the oversight and management of this working group.

@pcsmgnt and I met today to talk about some ways to improve OMI. One of the things that came up is how we manage our social media. Shirley proposed that we use a tool SEMrush to plan our content ahead of time and automate the posts. This allows us to be intentional with how we tell our story, and engage with the community.

**Comment by mrmetaverse** [comment]
At the present we shoot-from-the-hip for most of our social media. This approach could allow us to form a group focused on content for 2-4 hours a month to plan the content for the month. The publishing will be automated. 

I propose we review this tool, and we vote to form a content team.

**Comment by mrmetaverse** [comment]
@pcsmgnt shared this example content matrix: https://docs.google.com/spreadsheets/d/14r46E_6oUX-ORMvjfniQHZTw1y_UvURFOy2Ef9oRJ3w/edit?usp=sharing

**Comment by mrmetaverse** [comment]
2 paths: 

1. propose immediately to Wednesday meeting as a working group 
2. Get started, plan a small weeks worth of content and start using it with twitter THEN submit for review. 

I will be part of this group kickoff, and @pcsmgnt volunteers to oversee the effort as lead. Probably meet once a month for 2 hours to plan months content with the content team.

**Comment by pcsmgnt** [comment]
I have ear-marked 17:00 BST/12 EST for this meeting. I don't have access to create an event, is I guess we meet in an audio channel that is available at the time. 

For the agenda, I propose the following:

- Objectives
- Current state 
- Tools & Templates
- Content
- Frequency
- Actionees
