### ISSUE TITLE
Proposing UX Research Working Group

### ISSUE THREAD

**Issue by jetschni** [omigroup/omigroup#222]
# UX Research Working Group

Goal of this working group is to understand the existing experiences of Metaverse users, research their needs and pain points, and identify new path and opportunities. Overall, this working group aims to inspire builders to build products and solutions users love and accelerate the journey to the Metaverse.

We will start with a user research study, early key questions are (to be refined later):

- Who are the users of the Metaverse today?
- What are the frictions and challenges they face?
- What do people care about? What is important for them?
- What do people wish would exist?

Proposed lead for working group: Jonas Jetschni

**Comment by mrmetaverse** [comment]
Thanks Jonas! This is a group quite a few members have expressed interest in before. I also appreciate your willingness to lead the group and keep the efforts moving. 

I will bring this up for review tomorrow during our weekly OMI-wide meeting (at 16:00UTC / 12p ET). 

I also know that @Elirudite @fire @humbletim @technobaboo @jsejms and more are probably interested in the success of this group!

**Comment by Elirudite** [comment]
Definitely interested in this!! Wanted to make a proposal as well with a list of research opportunities to start with, but haven't had the time.

**Comment by robertlong** [comment]
We discussed this in our meeting today. Sounds like we have some interested folks! I think we should continue to gather feedback and interest. We can have a vote to create this group next week.

One thing I'd suggest is reaching out to existing researchers / research groups. Let's see if there are opportunities to collaborate with others. Even if OMI is joining in to represent the Open Metaverse in other established groups.

**Comment by mrmetaverse** [comment]
To get in touch with Jonas, you can reach out to jojet in the AngellXR discord :)

**Comment by jetschni** [comment]
We engaged with an experience researcher in the space to conduct the study. Currently looking for sponsors to support it.

**Comment by humbletim** [comment]
@jetschni Sounds interesting!

What else do we need to get this group off the ground? Also do you imagine collaborative research leading to formal specifications (at some point)? If so there may be some W3C alignments to consider similar to other OMI subgroups.

Also any thoughts as to how the proposed group could be structured (meeting cadence, incremental milestones, etc.)?

**Comment by mrmetaverse** [comment]
Great question @humbletim! We want to make sure a group like this has all it needs to hit the ground running. We can vote to form this group on Wednesday. @jetschni if this group is approved we will meet to define a regular meeting time/cadence (weekly/monthly/etc), a readme, a backlog and the first milestone: setting up this repo! 

It's fun kicking off projects, and this working group could make a real impact.

**Comment by mrmetaverse** [comment]
It's aaaaaliiiiivvee

**Comment by mrmetaverse** [comment]
This was bumped last week by another member of protocol labs. stay tuned.

**Comment by duckie-han** [comment]
Hi all - 
This hasnt been forgotten!

My name is HQ Han, I'm currently the Metaverse Lead at Protocol Labs, and also lead a few other teams in Filecoin ecosystem growth. Due to some change in plans - Jonas has left Protocol Labs hence sorry for the delay here in coming back. It would be nice if he continues to participate in this open source development though. 

UPDATE! -> I'm super excited to share that we've actually **recently completed the user study as described on the initial ticket** with a top-class web3 researcher & her team. And honestly - we are keen to keep this going as Part 2, Part 3.. and so forth.

We are really keen on the following:
- Sharing and discussing the findings with the OMI community
- Co-publishing under OMI and Protocol Labs to really drive the discussion forward in the broader community
- Participate in the recurring UI/UX research meeting -> shall we do this monthly?

**Comment by mrmetaverse** [comment]
> Hi all - 
> This hasnt been forgotten!
> 
> My name is HQ Han, I'm currently the Metaverse Lead at Protocol Labs, and also lead a few other teams in Filecoin ecosystem growth. Due to some change in plans - Jonas has left Protocol Labs hence sorry for the delay here in coming back. It would be nice if he continues to participate in this open source development though. 
> 
> UPDATE! -> I'm super excited to share that we've actually **recently completed the user study as described on the initial ticket** with a top-class web3 researcher & her team. And honestly - we are keen to keep this going as Part 2, Part 3.. and so forth.
> 
> Some things we hope to achieve:
> - Sharing and discussing the findings with the OMI community; especially with this working group once it's formed!
> - Co-publishing under OMI and Protocol Labs to really drive the discussion forward in the broader community
> - (might be an offshoot) Let me know if anyone can help on the design aspect of the report (visualisations from the findings, etc) to make it production-ready?
> - Marketing help from all our respective organisations 
> - Participate in the recurring UI/UX research meeting -> shall we do this monthly? 
> 

Hi @duckie-han, thanks for this update. Sounds exciting! We will review Wednesday at 16:00utc in our weekly meeting!

**Comment by Elirudite** [comment]
I'm very much excited for this as well!! I put together a simple research plan that I'd like to do myself geared towards the metamapping and traversal use cases:

https://docs.google.com/document/d/1hPjUo-7FzICbzZM5LkEUqzfaIfOM-FlW79odq0-nLnM/edit?usp=sharing

Can we do this in parallel?

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/183966442-5a64f5b8-1e89-4f20-a247-aa0c85fdd719.png)

**Comment by mrmetaverse** [comment]
In our discussion today, the group would like to consider how we could align on research together, maybe even in a virtual space (Jin). We are going to think on it for the week, and gather more thoughts from people like @Elirudite

**Comment by mrmetaverse** [comment]
Think we will vote next week on the adoption of the UX Research group. I created [this new UXResearch-pro-tem discord channel](https://discord.gg/G6uTzsqUak) for the adhoc group to meet and discuss. If the group is voted in by OMI next week, we will create a repo, README, and standard backlog for the group.

**Comment by LightLodges** [comment]
Cross-posted to the discord thread: Possible topics for UX Research group to address: portals and traversal UX/UI, UX of navigation (WebXR related - would potentially also sit with WebXR group), XR UX & Accessibility (may also collab with W3C working group), UX R&D topics related to health and safety impacts, other topics you'd like to bring to the table?

**Comment by mrmetaverse** [comment]
I met with @duckie-han today! 

I was able to get a lot more clarity around the proposed collab with the protocol labs team. 

- Let's discuss the results, and share the research in a UX research group. If the working group decides to keep working on the research great! But Protocol cares more about discussing their research and collaborating, they are not looking for OMI to "just add our stamp of approval." 
- The research they did has a lot of fun open ended questions for continuation. They want to use their report as a primer for conversation! 
- Hoping to refine the report and increase the sample size. 

They are not sure if they have the guaranteed bandwidth to _lead_ the working group, and hope we have someone.

**Comment by mrmetaverse** [comment]
Vote approved: 


![Image](https://user-images.githubusercontent.com/63426722/189944921-39826985-cba9-4227-ab91-93ed60ca99e9.png)



repo formed and first milestone formed: https://github.com/omigroup/ux-research/milestone/1
