### ISSUE TITLE
Bi-weekly OMI Developer Hour

### ISSUE THREAD

**Issue by robertlong** [omigroup/omigroup#225]
The Scripting Group originally set out to have an alternating meeting cadence where we have a specification session and the next week we have a demo session. In the last couple weeks we've been using our time to talk about general tech topics and it's been a ton of fun chatting with people about techy stuff. I'd love to repurpose this time and make it a more general OMI developer hour. People could come in and chat about metaverse development, share what they're working on, etc. It'd be pretty informal, just a good time to build community with one another.

So the details would be every other Tuesday at 9:00 AM (or we could find another time). We'll have an hour where we just chat about metaverse development. The scripting group will then meet in the other bi-weekly schedule. And if you mess up which week is which, you'll still be in a place where you have fellow devs talking about developing the metaverse.

**Comment by mrmetaverse** [comment]
The scripting group adopted a bi-weekly cadence for this.
