### ISSUE TITLE
react-emoji system

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#232]
- To limit number of bots, a react-emoji system would be ideal. 
- A voting bot would be ideal.

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/229#discussioncomment-2731975_

**Comment by humbletim** [comment]
📰 @fire and I are taking a look into react-emoji strategies to help capture and report on notable discord messages.

ideally, we hope to find something that's not just limited to voting, but can be applied to both administrative and other noteworthy OMI activities.

**Comment by fire** [comment]
We tested it and worked, but ultimately didn't deploy. Stale issue.

**Comment by mrmetaverse** [comment]
@fire you tested it, it worked, but it didn't deploy. What was the blocker for implementation? Is there a next step in mind or was it not worth the squeeze?
