### ISSUE TITLE
RE: Discord

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#233]
RE: Discord 
We need to geta better handle of our recurring events. CC: @robertlong to create ticket

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/229#discussioncomment-2731965_

**Comment by fire** [comment]
I believe we're using mee6 both. What is the status of this?

**Comment by mrmetaverse** [comment]
What is the status of this? I will archive in 2 days

**Comment by fire** [comment]
I have heard no movement.
