### ISSUE TITLE
Audit Existing bots

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#234]
We have a bot problem. In that we need to define our bot processes. What bots are installed? Who can help fix bots that break? how do we handle security vulns with bots?

**Comment by pcsmgnt** [comment]
I would like to remove Carlbot. It was installed to welcome people, but this feature already exists with MEE6 and there is no point having an additional bot just for it. Furthermore, I polled it removal and people voted for it to be taken away, so I think Carlbot should go.

That being said, I have added and deployed Craign recording bot for our meetings. It is working well and I suggest we try it out for a while until we can ascertain why the MEE6 recording feature is acting up.

**Comment by fire** [comment]
I did support carlbot, but if we don't use it, only essential bots should be kept.

**Comment by mrmetaverse** [comment]
bump

**Comment by mrmetaverse** [comment]
final bump, moving to tomorrows agenda

**Comment by mrmetaverse** [comment]
Bots mentioned today during champions

**Comment by mrmetaverse** [comment]
How many bots are in the server, who has access to the bots, how do we decide on who should invite bots? 

Do we define a bot-team?
