### ISSUE TITLE
Privacy: Teleport, Ghost or Mute on Arrival

### ISSUE THREAD

**Issue by knev** [omigroup/omigroup#238]
# Privacy: Teleport, Ghost or Mute on Arrival

## Contributors

- Kim Nevelsteen, PhD; Root Interface AB

## Summary

When a user on the web today clicks on a link, they are moved to another website, but this act is anonymous. When teleporting between 3D worlds, the user is potentially thrown into an environment where immediately their handle, avatar and or open mic is shared with the users in the destination world. On some browsers, the user must actively click to enable their audio. This concept can be extended to Ghost or Mute on Arrival.

a ghost is where: avatar, user handle, and presence isn't immediately visible to others.

## Example Use Cases

When a user arrives in a new 3D environment from a teleport, the user is placed in the new world as a ghost or at least with their mic muted.  When the user interacts with the world, their ghost status can be revoked and the mic possibility turned on if the user so specifies.

## Implementation

Rather than create a lobby for new users, users are placed in the new world, with or without being able to see participants of the world. The avatar of the new user is not rendered for other participants, and the new user's arrival is not announced. From the user perspective, their avatar is perhaps rendered translucent in 3rd person or with some kind of full screen visual cue in 1st person. A symbol can be placed on screen to show that the users mic has been muted. This point might be an opportunity for the user to change their in world appearance before entering the world. 

Clear controls should be placed on screen where the user can un-mute their mic. Interaction with the world can make the user enter the world. Leaving should always be an option through a "Back button" or just closing the interface to the world.

**Comment by mrmetaverse** [comment]
Overall, this is interesting conversation fuel: 
antpb: How could we standardize this? Is this a recommendation, UX pattern, protocol, or something else? 
mal: It's important that many systems don't allow people to be invisible to people in the space. Mainly from a privacy standpoint. 
A.: in a game, an environment where there may not be other players, it would be nice to be able to enter on pause to acclimate to your surroundings. 
f: Maybe this would work as an entry placeholder 
- this comes into play when we talk about metatraversal as well though, like if you can portal into another world, and see the other world in that portal, is that any different from a privacy standpoint as it relates to being able to enter invisible? 
A. in the gLTF group, humbletim brought up interesting points about how placeholders could be implemented in Worlds, so this is relevant to that too.

**Comment by mrmetaverse** [comment]
Reviewed and archiving <3
