### ISSUE TITLE
MSF Delegate

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#250]
# MSF Delegate

About 2 weeks ago, the Metaverse Standards Forum was announced. We have been speaking as a group over the last two weeks about how we see ourselves engaging with other groups and through forums like MSF. 

We should consider appointing a delegate or delegates to participate in MSF regularly, representing OMI, and channeling communications and updates to our community. We want to be intentional in how we engage with forums like MSF, and put our best foot forward inciting real change in Metaverse Interoperability. We recognise the need to be reliable and present to explore MSF and ways we can continue to champion Metaverse Interoperability. 

Do we want 1 or many? Do we have any volunteers? What does this role entail? 

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/249#discussioncomment-3087129_

**Comment by mrmetaverse** [comment]
>"If there are other big tech firms involved, we may need more seats at the table and not less. We need our own seat at the table (OMI direct), someone from W3C representing us too, and our community members each with their own seats at the table representing their own entities. We need more voices / a bigger voice, to ensure we are heard alongside the larger corporations participating in MSF."

**Comment by mrmetaverse** [comment]
During todays meeting it was proposed that we explore forming our own Non-Profit

**Comment by mrmetaverse** [comment]
Volunteers: 
- funksoup 
- Shirley 
- Mike (Icosa)
- humbletim

**Comment by mrmetaverse** [comment]
Moving to in-review. 

Applied to MSF as participant. Using the omigroup.org email handle. I assigned the primary contact as msf-delegate@omigroup.org and will create that email next. 

cc: @funksoup @humbletim @ Mike @pcsmgnt - I recommend you set a time to meet as a group (feel free to start a discord chat and add me to it). 

![image](https://user-images.githubusercontent.com/63426722/179796240-e92cf206-a018-46d8-ae70-ec4804c87e6b.png)


[OMI-MSF-SIGNED-Please_DocuSign_Metaverse_Standards_Forum_Pa.pdf](https://github.com/omigroup/omigroup/files/9142783/OMI-MSF-SIGNED-Please_DocuSign_Metaverse_Standards_Forum_Pa.pdf)

**Comment by mrmetaverse** [comment]
Funksoup initiated a group DM to move forward as delegates!

**Comment by mrmetaverse** [comment]
We signed up OMI a few days ago, and are still waiting for the logo to get added. The only task left for that is to create a msf-delegate@omigroup.org email and ensure that all of the volunteers have access to it (or however the MSF delegate group wants to manage that email). 

- [ ]  create msf-delegate@omigroup.org
- [ ] ensure all volunteers have access as decided in the group organized by funksoup

**Comment by mrmetaverse** [comment]
Quick updates: 
- Created a channel `omi-msf-delegates` in Discord. 
- OMI was officially added to [MSF site](https://metaverse-standards.org/)
- Recognized in the "constellation of standards" on the home page
- We may not need to create another email, as one delegate was able to join OMI org with their primary email (and not their omigroup email) with express written confirmation.

**Comment by mrmetaverse** [comment]
Kicked off today 
@humbletim should we create a repo too?

**Comment by humbletim** [comment]
(breadcrumb) notes from first MSF Delegates meeting: https://github.com/omigroup/omigroup/discussions/256
