### ISSUE TITLE
Create sign up for OMI Interoperability Demo Day 2 - 07/27/22

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#255]
On Wednesday July 27th, 2022 at 16:00 UTC, OMI will host and stream our second Open Metaverse demo day. Presenters can share demos of the past, present, or future, from any category in the `open metaverse`. 

This issue is to track volunteers to speak. We will try to get to everyone. You can [sign up to present here](https://docs.google.com/forms/d/e/1FAIpQLSfwrdJQ4hk-nc9t9-qG_UfCkzTQE1Cd1QyLVMMs4y9asLdnmQ/viewform)

**Comment by mrmetaverse** [comment]
# Volunteers

**Comment by mrmetaverse** [comment]
- Codefrau
- Robert
- RedEagle

**Comment by mrmetaverse** [comment]
There is a Google form for this effort. 
- [ ] I will find the link and add to this ticket before moving to done 
- [ ] I will edit the links on other discussions that say "sign up here" to direct to the Google form

**Comment by LightLodges** [comment]
Add Jon Yu, Elysium/Mythologi.es -- open AR tools to demo (from form)

**Comment by LightLodges** [comment]
https://forms.gle/gZG3Tbn3EnBLDYin8
