### ISSUE TITLE
Demo of Dework.xyz

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#285]
Can we get a demo of dework? 

## Source: 
Q: What about something like [dework](https://app.dework.xyz/bounties), do we want to use bounties?

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/284#discussioncomment-3519768_

**Comment by madjin** [comment]
Happy to do a presentation / demo anytime!

**Comment by madjin** [comment]
I gave a presentation during the last 15 minutes of this weeks meetup. I propose we run a small experiment with 1 of the working groups like @omigroup/media to trial [Dework](https://dework.xyz/) by way of:
- Decide if we want to integrate Discord
  - Dework can create threads in threads inside specific media channels in our discord
  - Gives visibility to everybody on the server on actions happening in Dework
- Integrating Github
  - Importing issues (1:1 Github integration possible)
  - Prioritizing as an organization what tasks we wanna work on
    - We can have multiple reviewers per task if we wanted
- Deciding and allocating a small one-time trial budget to media org
- Summarize into a presentation / demo for the rest of the organization on how it goes

Suggest only picking small lightweight tasks, such as things that can have multiple submissions (taking notes at meetings, summaries, blog posts, etc). Happy to get this started and teach others what I know (been using Dework for 5 months now)

**Comment by mrmetaverse** [comment]
Demo done, was there any other outcomes from this?
