### ISSUE TITLE
Let's learn from Sindhu

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#303]
Let's learn from Sindhu, who has extensive experience as both a Scrum Master, and Project Manager. Sindhu has identified a few gaps in our communication approach to help people actually get involved and get work done. 

What can we learn? How can we channel those learnings into our working groups who want to learn? 

Maybe use this ticket as a example ticket to track the journey per @fire 's recommendation. 

Shirley mentioned we have systems in place it may just not be obvious where those are. 

RedEagle has been advocating for a welcome process for onboarding newcomers. 

Jin has been an advocate of posting known tasks/tickets on a site like dework.xyz to incentivize known to-do's. 

Many people shared concerns that we may be losing people who don't come back because they can't easily see how to get involved. 

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/302#discussioncomment-3862513_

**Comment by sindhu-raju** [comment]
Hi Everyone, I am going through several items and will make a list of comments/suggestion.

**Comment by mrmetaverse** [comment]
Thanks! We are cleaning up our backlogs. I will sync with you when you return @sindhu-raju and we can talk about the next iteration of our processes.

**Comment by mrmetaverse** [comment]
## Action items (jan 3, 2023) 

1. Omi structure -  I think most of your problems reside in not sticking to a tried and true structure and a roles and responsibilities document. It is in not clear who the champions are and what are their responsibilities.

I would take a look at the board of directors structure… and their responsibilities.
https://aprioboardportal.com/news/nonprofit-board-structure/

2. Website - I gave Shirley my comments. For onboarding just get it down to one page and only include working groups with contact information. Do not put up archived groups.
3. I worked with EVO on documenting guidelines for external conferences. It is in her hands and should be brought forward for approval.
4. MSF - I started some documentation/project charter for MSF. This was more of a document so people could know who was working on what. Shirley and Funksoup have access. My only comment on MSF is that we should push back on big companies only having access. It is important for individuals to contribute.
