### ISSUE TITLE
Invited  Rep from Tech Circus to some and discuss the upcoming event with the community

### ISSUE THREAD

**Issue by pcsmgnt** [omigroup/omigroup#308]
Invited  Rep from Tech Circus to some and discuss the upcoming event with the community. They are looking for speakers and it would be a great opportunity for members of the community to showcase their work/projects/expertise.

**Comment by mrmetaverse** [comment]
End of November, in the UK
LINK TBD:

**Comment by pcsmgnt** [comment]
Link: https://techcircus.io/en/events/enter-the-metaverse-london-2
