### ISSUE TITLE
Create an emoji or specific identifier for discord that passes github and this theoretical weekly chronicle into a summarized list of "what happened this week/month"

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#337]
maybe something like starboard bot, people can star things, and a leaderboard is created with a summary of what happened.

**Comment by mrmetaverse** [comment]
![Image](https://user-images.githubusercontent.com/63426722/216187827-a9e8136e-5dae-4648-9685-8d763005b996.png)

**Comment by fire** [comment]
@RedEagleP1 What steps do we need to accomplish this?

**Comment by fire** [comment]
1. https://top.gg/bot/655390915325591629
2. https://carl.gg/

**Comment by mrmetaverse** [comment]
- [ ] Select or create a new emoji
- [ ] Choose a bot (we haven't found one that we like before)

**Comment by mrmetaverse** [comment]
We have had issues with bots in the past, so we need help selecting one.

**Comment by fire** [comment]
https://github.com/AnIdiotsGuide/discordjs-bot-guide/blob/master/coding-guides/making-your-own-starboard.md was mentioned

**Comment by madjin** [comment]
I will run a weekly cronjob to screenshot and archive `omigroup/omigroup` and `omigroup/gltf-extensions` GitHub discussions and archive such here: https://github.com/omigroup/omi-archive

Afterwards I think we can close this issue and mark as complete

**Comment by fire** [comment]
@madjin did you do the tasks you listed?
