### ISSUE TITLE
Operationalize a monthly recap of OMI accomplishments

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#338]
If we had a summary: 

- we could post on our website and socials (media and awareness boost) 
- we could grab recent tickets completed 
- we could snag screens from recent demos 
- we could help newcomers understand our work better 
- we could inform the press regularly of our efforts 
- getting people excited! WOW I want to be part of this 
- solid foundation for grant applications
  - you can prove your prev accomplishments and justify grant funding based on that. 
- Build more awareness of the awesome work OMI working groups are doing so that our efforts don't get eclipsed by other 'open metaverse' efforts

**Comment by madjin** [comment]
Some kind of monthly changelog of accomplishments can be fed to writers / AI to generate blog posts

I have some useful ideas + snippets of code here for pulling info from github discussions:
- https://hackmd.io/c4F5vAZCQeGPlyj151biQA

@antpb is making booths for visualizing OMI glTF extensions activities

We now have a better system for distributing crypto bounties for things using dework + safe
- https://app.dework.xyz/omi-group/test-83954/overview
- https://app.safe.global/eth:0x5ac59c41A552df8E710b3c72D906f878D9075bD2/home

Can make a bounty for the people who do work of compiling the information and creating the monthly recap

**Comment by fire** [comment]
mtv is connected to evo to join the media team.

**Comment by mrmetaverse** [comment]
related #337
