### ISSUE TITLE
We could use more industry connections, to get more voices heard, and get our stuff adopted

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#341]
The groups that keep popping up, trying to standardize the metaverse, are forming industry connections. 

- who is out there? 
  - who are our allies? 
  - who else could be allies?
- when we are in those meetings at MSF, etc. We want other people in the room to back us up 
  - we need votes in these scenarios 
- This is also related to beefing up our media strategy, and sharing monthly recaps of our accomplishments 
- Related to the more-delegates concept. 
- Reach out on LinkedIn! "hey just saw you got elected as chair of group x, we have this stuff going on here, and would love to collab" 
- Enhance genuine authentic relationships with the other groups out there 
- what can we learn from Khronos collab, MSF-delegates, OMF launch, Open Metaverse Conference collaboration (lamina1), etc. 
- More people involved over all would enhance our capabilities. Imagine having 50 people in our next glTF group. 
- Maybe we can have more social gatherings, cross-collabs, and open meetings in each other's communities
- whats our follow up strategy for newcomers too? 
  - getting them activated!
- what brought you here? Why do you want to solve this problem? 
- _"booth displays of OMI group projects such as the glTF extensions (antpb working on this) + virtual expo event could help form more industry connections, then people can literally come to the table, https://github.com/NEON-BUIDL/booths I organized a bunch of templates here if you want to display ur project with one of them"_
  - If there were a space as a virtual office, a place to belong, and run into each other. 

## Let's form 2 new meaningful partnerships with other Industry influencers in the next month.

**Comment by mrmetaverse** [comment]
related #233

**Comment by fire** [comment]
The last item https://github.com/omigroup/omigroup/issues/342 is split into its own issue.
