### ISSUE TITLE
Create a spec for a virtual office, a place to belong, and run into each other.

### ISSUE THREAD

**Issue by fire** [omigroup/omigroup#342]
If there were a space as a virtual office, a place to belong, and run into each other.

"booth displays of OMI group projects such as the glTF extensions (antpb working on this) + virtual expo event could help form more industry connections, then people can literally come to the table, https://github.com/NEON-BUIDL/booths I organized a bunch of templates here if you want to display ur project with one of them"

**Comment by madjin** [comment]
- https://framevr.io/omi
- https://github.com/NEON-BUIDL/booths
- https://sketchfab.com/m3org/models

+ OMI Diner



![Image](https://user-images.githubusercontent.com/32600939/216702423-4a5026aa-d6ed-49e6-a3d1-bd9af38b387a.png)

**Comment by fire** [comment]
* Can build on wordpress and croquet
* Provide source materials for all

**Comment by fire** [comment]
Before the meeting visited a scifi high rise office with rainwolf.

**Comment by madjin** [comment]
I think the final deliverable should be a glTF object(s) so that it can be portable

Example: M3 HQ

![Image](https://user-images.githubusercontent.com/32600939/216706805-fccc3de9-04df-49b4-b80f-e4f940d8734d.png)

**Comment by fire** [comment]
From rainwolf:

https://vrchat.com/home/world/wrld_d8a747dc-854a-4712-b0e3-13bc3d9cf817

![image](https://user-images.githubusercontent.com/32321/216706786-fed3ed24-8e78-42ba-bd56-866a94c8f376.png)

![image](https://user-images.githubusercontent.com/32321/216706818-91db1a65-a475-4be9-9566-d068ffe6a45d.png)

![image](https://user-images.githubusercontent.com/32321/216706845-590bddd5-af2f-4373-9aa2-e675ebe538f5.png)

**Comment by fire** [comment]
Want to call it a space:

1. content space
2. structure space
3. outdoor space

**Comment by fire** [comment]
File size limits:

1. cushions for 25/50 people
2. outdoors are enjoyed more according to Evo

**Comment by fire** [comment]
Fun tone.

A place to start a tour. "Wander off in an infinite loop."
