### ISSUE TITLE
Swag creation update for the next weekly omi meeting.

### ISSUE THREAD

**Issue by fire** [omigroup/omigroup#354]

**Comment by mrmetaverse** [comment]
We have merch here: 
- https://my-store-ad6ddd.creator-spring.com/listing/omigroup-light-text?product=227&variation=2661&size=1245
- https://my-store-ad6ddd.creator-spring.com/listing/omi-open-metaverse-logo?product=934


Need: 
- [ ] stickers
- [ ] any other designs?
