### ISSUE TITLE
Verify / align OpenCollective status and website donate button ("501c... language")

### ISSUE THREAD

**Issue by humbletim** [omigroup/omigroup#355]
(thanks to `avatarjoy` for researching this further and bringing to our attention!) 

Current website donation blurb (scroll down on https://omigroup.org/):
![image](https://user-images.githubusercontent.com/94753/216708750-641f86a8-b528-424b-a4ba-6e6808457d1f.png)

- Apparently, there are different "fiscal host" options available through OpenCollective...
- OMI Group currently seems to be hosted under the "Open Source Collective" option (which is 501c6... _not_ 501c3)...
- OpenCollective also offers the "Open Collective Foundation" fiscal host (which _is_ 501c3, and does seem to offer tax-exempt donation options)
- It is not entirely clear which fiscal host would make sense, or if there were reasons for choosing "Open Source Collective" vs. "Open Collective Foundation;" it's also not clear yet what we might need to do if wanting to "switch" over to the 501c3 fiscal host option.

From https://docs.opencollective.com/help/financial-contributors/financial-contributors:
![image](https://user-images.githubusercontent.com/94753/216709515-e00d3c47-ee74-4e26-8afd-ed9a737261b9.png)

SUGGESTED ACTION ITEM: Research switching to OpenCollective 501c3 fiscal host; and/or update website language in short term to avoid giving potentially wrong impression of 501c3 / tax-exempt status.

**Comment by LightLodges** [comment]
We originally requested the fiscal sponsor relationship with Open Collective under the 501c3 and was told that as soon as there is a grant that makes that needed and viable we can absolutely shift into that -- and yes, there's a second agreement to put in place.
