### ISSUE TITLE
Proposing OMI-Experiments group 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#368]
# OMI-experiments

When we initially created OMI-WASM, there was tremendous excitement for the initiative. This lead to a broader OMI-Scripting effort, which garnered even more support. Ultimately, the effort became "blocked". 

I have often heard "where do I put things I am experimenting on," and "where is it appropriate to share my challenges and ask for help?" I hoped the UX-Research group could be a place where people "bring their problems worth solving". I still think the UXR group could become a major driver of our innovation and the Metaverse overall. 

However, I can't help but think there is a gap. I'd like to propose an OMI-Experiments group (or some other name) where people can gather 1-2 times a month to share their recent experiments, collaborate, and even draft protocols beyond our glTF work. 

There is a channel on discord called #omi-experiments where you can start sharing your work now, but I'd like to propose a recurring meeting. Scripting/WASM was a chance for us to really double down on our impact.

**Comment by madjin** [comment]
I would be down to cross-promote with M3 to participate if it were an in-world event (can help with such too)

**Comment by mrmetaverse** [comment]
- for glTF work, bring it to glTF group 
- for other things, other experiments this could be a great use-case

**Comment by mrmetaverse** [comment]
- a place to do "everything else" 
- sounds like a demo day of sorts too or show and tell of sorts 
- not just demos, but even if you want to build a demo and need advice/help 
- maybe you want to call people in for experiments you are working on 
- a place where groups like MSF delegates could request help prepping for world-hopping, etc.

**Comment by mrmetaverse** [comment]
Open Mic Night for Tech Challenges

**Comment by mrmetaverse** [comment]
This does roll up fragmental efforts into a collection zone. 

Are there any groups we can consolidate into experiments? 
- i.e. maybe we merge UX research group in to experiments, until enough people want a separate UXR group. Keep the channel open though. 
- portals 
- AI 
- events
- ISPME experiments
- mapping the metaverse

**Comment by mrmetaverse** [comment]
ad hoc the existing channel, review in 2 weeks to see if we vote

**Comment by karunakaruna** [comment]
I would like to see this too - Spoke to Jin about a place to share short presentations about what people are working on - though this sounds like it might be more for people the software/extensions and standards? Would this be an appropriate place for world-builders to also share their work? If not then I will plan to organize a separate event. Though the cross-over between the two groups might be interesting.

**Comment by mrmetaverse** [comment]
related #374

**Comment by mrmetaverse** [comment]
related #364
