### ISSUE TITLE
Proposal: Finding our "first 5"s

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#416]
In the spirit of growing our implementors and our contributors, I'd like to propose these goals for review. 

Lets find our first 5. 

- `5` examples of creators  using OMI_Seat, OMI_Physics, and OMI_Personality 
- lets find our first `5` platforms to implement 1 OMI protocol. (maybe OMI SEAT and OMI Physics)
- `5` outside submissions proposed for OMI review 

Lets host a OMI demo day to celebrate each category. 

We can change numbers, and this is just a proposal. But I believe these goals would provide a foundation we need to build on.

**Comment by knev** [comment]
As I mentioned in the weekly meeting. Rather than "demos", I think it would be more advantageous to start building and reaching milestones that can be built upon to reach the next milestone.

**Comment by mrmetaverse** [comment]
Demos are a celebration and check-in. Its a reflection on progress. The goal is defined, the demo is showing the results.
