### ISSUE TITLE
update W3C and get new chair access to update

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#438]
update W3C and get new chair access to update

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/issues/437#issuecomment-1896287378_

**Comment by mrmetaverse** [comment]
Update:

I can log in to the w3c page and post blogs. That might be useful for the media team. Maybe we can sync this wordpress and our own site. Maybe that was already done. 

![image](https://github.com/omigroup/omigroup/assets/63426722/819eb490-a239-401b-941b-cdaa857e6198)

I cannot find how to update the chairs. But I do see that you must have a W3C account to do certain things like manage the page. 

Your moves: If you want access please create a account and follow the instructions to join our W3C page. 

My moves: I will email W3C and see how I can add Indie as a new chair. 

We should prepare to announce the new chairs and thank the previous.

**Comment by indiebio** [comment]
I have an account, I have joined the group, and see I can send to the mailing lists (public and internal). (which is what I needed so happy-ish)
I do not see how to edit this page, which is needed sooner than later: https://www.w3.org/community/metaverse-interop/

**Comment by mrmetaverse** [comment]
done! thanks @indiebio
