### ISSUE TITLE
Set up the bots for the new discord server like the ones we use in the Angell XR discord.

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#443]
In our [new discord](https://discord.gg/YGpDbCu7EU), we would like to have the same useful bots as the Angell server, so that we can automate things like event reminders, roles, and recordings. 

- [ ]  "Who set up the bots on this Angell XR server? It would be nice if those people could do the same for the new server."
- [ ] "OMI-related event reminders should be moved to the new server as well."

**Comment by indiebio** [comment]
things to add
1 - google calendar sync to Discord
2- announcement bot that is linked to that
3 - the recording bot

**Comment by madjin** [comment]
got 2/3, need to transfer mee6 premium to new server (I can't do it)

**Comment by mrmetaverse** [comment]
![image](https://github.com/omigroup/omigroup/assets/63426722/dfffd850-1ac1-4b63-8487-be569365fcef)

@madjin
