### ISSUE TITLE
vote passed! switch the logo on all channels

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#445]
vote passed! switch the logo on all channels
![image](https://github.com/omigroup/omigroup/assets/63426722/1f54cab9-45a3-46e1-b488-c57c5ee1dd30)

Places to switch: 
- [x] discord
- [x] website
- [x] [figma](https://www.figma.com/file/7IkelFTsQPpMwzrWGzqFBA/Omigroup-Designs?type=design&node-id=2227%3A432&mode=design&t=0aDSm4rcSw6c2R7w-1) design system 
- [ ] w3c
- [x] socials (twitter, youtube, and masto) 

_Originally posted by @mrmetaverse in https://github.com/omigroup/omigroup/discussions/442#discussioncomment-8469660_

**Comment by mrmetaverse** [comment]
![image](https://github.com/omigroup/omigroup/assets/63426722/56557d29-8263-4dd0-8243-f89215592844)

**Comment by mrmetaverse** [comment]
we will discuss the status at todays meeting.

**Comment by mrmetaverse** [comment]
to update the w3c logo this is related #438

**Comment by musicscene** [comment]
Update:

download png logo from: https://github.com/omigroup/omigroup/issues/445#issuecomment-1944324000
updated logo on github
found many of the discord links were expired...
created new unexpiring github invite link: https://discord.gg/Rypf8Kc6CZ
updated discord link on github profile
updated discord link on github home page
updated discord link on github media repo 
updated discord link on github MSF-Delegates repo 
updated discord link on github omigroup repo (requires review)
updated discord link on github omi-scripting-group repo (requires review)
updated discord link on github gltf-extensions repo (requires review)
updated discord link on omigroup.org
updated logo in lower body of page, but top seems to belong to a hidden block/nav section that I dont have acess to.

Todo: 
verify if we should be using svg

complete website:
update discord link on github omigroup repo (requires review)
update discord link on github omi-scripting-group repo (requires review)
update discord link on github gltf-extensions repo (requires review)
update logo in top of page

continue to review
w3c
twitter
youtube
mastodon

**Comment by mrmetaverse** [comment]
status on this?

**Comment by mrmetaverse** [comment]
should be done, and can be done case by case moving forward
