### ISSUE TITLE
Weekly Meeting 107 is happening on Wednesday, May 17, 2023 from 9:00 AM PST (16:00 UTC) - 10:00 AM PST (17:00 UTC)

### ISSUE THREAD

**Issue by 1coolmatt8083** [omigroup/omigroup#454]
Weekly Meeting 107 is happening on Wednesday, May 17, 2023 from 9:00 AM PST (16:00 UTC) - 10:00 AM PST (17:00 UTC)

You can add it to your calendar [here](https://calendar.google.com/calendar/u/1?cid=Y18wZHB1Z2Y5ZjgzZXE0cWVrbWI2b21xYmptZ0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t).
 
We'll be meeting again in the omi-weekly-meeting channel of the [AngellXR/OMI Discord](https://discord.gg/NJtT9grz5E).
We regularly use the # omi-meeting-chat channel for text chat. 

## Who we are and why we're here:

The Open Metaverse Interoperability Group (OMI) is focused on bridging virtual worlds by designing and promoting protocols for identity, social graphs, inventory, and more. Our members include businesses and individuals working towards this common goal. 

If you’re an observer or here for the first time, this is a meeting where people who work on the OMI group initiatives discuss updates and contribution opportunities for current projects and goals. This is your chance to jump in and help!

We welcome you to introduce yourself in #omi-meeting-chat as we dive into the agenda items. There will be an open floor in the last 15 minutes of the meeting (agenda permitting) where we can discuss any items you feel are relevant to the current or near future OMI goals.

## Agenda

UPDATES:

MSF-delegates:

- There is a board election coming up - it's important that we/OMI have a representative on the MSF board, so we can continue to be a voice for independent creators, small orgs, open source and community/grassroots orgs. Elections will be in a few weeks but we can start preparing our community for that now. (There are some documents we will need to fill out).

- Interoperability issue to bring to the attention of MSF and industry in general (via @aaronfranke):
-- There are competing standards between OMI's [OMI_collider](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_collider) and [OMI_physics_body](https://github.com/omigroup/gltf-extensions/tree/main/extensions/2.0/OMI_physics_body) glTF extensions and Microsoft's physics https://github.com/KhronosGroup/glTF/pull/2257.
-- Evo will interview @aaronfranke and then post the video so that we can get more engagement on this issue.
-- How can we get more engagement? Email the MSF general list (but make the email shorter - make ask clear)
-- Evo suggested Ben Houston at ThreeKit - maybe hit up specific people like this on LinkedIn?

-- Issue is described in detail in this [OMI_collider and OMI_physics_body pull request](https://github.com/KhronosGroup/glTF/pull/2258) and there's a bulleted list of specific differences and impacts. 

Media group: 

GLTF group:

WORLD HOPS:
Status of metatraversal world hop? Real world/virtual world hybrid event for [AWE](https://www.awexr.com/)
AWE conference is May 31-June 2 in Santa Clara, CA. If we can get some folks who will be onsite at AWE to help facilitate, we could do an OMI metatraversal world hop, similar to what we did at the OMI 100th meeting anniversary event. 

We could visit / meet in these spaces (via @madjin): 
https://hyperfy.io/msf
https://hyperfy.io/neonstreet
https://hyperfy.io/omi
https://framevr.io/omi

-- Keyframe will also be planning an event on May 24 - 'Workshopping the Metaverse' in Spatial. Will be an open format -- people invited to come and ask questions. Do we have OMI slides for him to use? (Check with @mrmetaverse).

- We will need folks to be welcomers / hosts that can facilitate people joining the world hop to meet & greet.

To follow up on organizing the proposed world hop for AWE, we can use our [pro temp events channel in Discord](https://discordapp.com/channels/770382203782692945/1052644259741843526).

_Originally posted by @funksoup in https://github.com/omigroup/omigroup/discussions/390_

**Comment by aaronfranke** [comment]
May 2023 was 10 months ago, sorry.
