### ISSUE TITLE
Create OMI weekly meeting discord bot

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#63]
## Context
In order to ensure we are consistent with updating the agenda, publicly documenting our attendance, and establishing an effective system for voting, we need a discord/matrix bot that can document and automate some of our processes.

### Acceptance Criteria: 
- Takes attendance 
- Track voting 
-  _need a list of usernames for these people_

### Bonus: 
- It can provide reminders (alternative to old bot)
- The bot automatically starts and shares a github discussion or hackmd for the meeting that pulls the agenda from github, and adds the attendance, and results of any votes.

**Comment by auscoi** [comment]
Not sure how to "assign" myself to this but I'm down to work on this issue and will try to get at least a skeletal bot up and running by next week. It will be a Python/Redis based system (discord.py is a wonderful wrapper and kept very up to date). Once its up we can add functionality as needed.

**Taking Attendance**
- How do we verify this? Simply joining the live meeting chat? Or will it be a manual command that each member will have to input during the specific window?

**Track Voting**
- I had already started on a polling/voting system for another bot of mine but apparently lost a lot of code progress somewhere along the way so I have it in my head how it works but will have to redo a lot of it...

**List of Usernames**
- I usually prefer registration with my bots anyway so as not to pollute the backend with unwanted userdata
- Something like a basic "?register" command

**Reminders**
- I've already built an automated announcement system, can import that easily ;)

**Comment by humbletim** [comment]
(just for reference) here are @jsealt's 7/21/2021 Weekly Meeting 13 notes from earlier today:

## Discord Bot 
We created issue [#63](https://github.com/omigroup/OMI/issues/63) to build and deploy a discord bot for our server that will manage some of the tasks. 

In order to vote you have to attend 2 consecutive meetings first. So we need to track attendance and voting eligability, as well as track the results of votes. 

As added bonus it would be ideal if the bot could pre-draft the next weeks agenda, automatically spin up a hackmd markdown file. 

To get involved please reach out on OMI Github. 

- Requested volunteers
- Would python or JS be limiting? 
- Cause suggested keeping it simple 
- Nova suggested python for its string management. The two are so similar at this point you can do most tasks with each other. 
- Would be cool if we could get more info on setting up a Matrix server :joystick: 
- Cause volunteered to help lead this effort next week.

**Comment by mrmetaverse** [comment]
Do we have a status update on this effort? 👀

**Comment by auscoi** [comment]
Apologies I just got back from a family reunion all weekend out in BFE with no Internet access so my life sort of backed up over those disconnected days. I've gotten a nice little barebones skeleton of a bot started but its not quite ready to toss into the server. I'd hoped to get more done before the meeting tomorrow but hopefully I can get it at least in the server and saying Hello World by the end of the day tomorrow :P

**Comment by mrmetaverse** [comment]
> Apologies I just got back from a family reunion all weekend out in BFE with no Internet access so my life sort of backed up over those disconnected days. I've gotten a nice little barebones skeleton of a bot started but its not quite ready to toss into the server. I'd hoped to get more done before the meeting tomorrow but hopefully I can get it at least in the server and saying Hello World by the end of the day tomorrow :P

Sounds good! Progress is progress. Just wanted to check in with you before adding it to the agenda for today 😅

**Comment by madjin** [comment]
For attendance can use https://poap.xyz/

**Comment by mrmetaverse** [comment]
BLOCKED/ REFACTOR: 

Developers of discord py is getting retired.  

Identify a new method of working with custom discord bots that support slash `/`commands.

**Comment by mrmetaverse** [comment]
Bump: Sharing a comment from @auscoi  From 10/1 :tada: 

>I'm really loving the discord.js library and how it works with the slash commands as well as all of the hidden UI components I didn't even know Discord had like those buttons on Apollo scheduling announcements for example.

>I am eager to begin learning Node anyway as it will tie into a lot of other projects I'm working on as well. Like I mentioned in the meeting before I have started a bare bones skeleton of a bot honestly just following the guide that discord.js put out themselves. It's pretty comprehensive and takes you right through it. My previous bot experience is definitely helping me grasp concepts a lot quicker I'm sure but still it was pretty cool. 

>I'd like to recreate the base level bot for OMI Chan I already created in Python as I had a lot of things like graceful errors and response outputs of language and reactions nicely figured out (sort of my own little sub API). Once I get there I'm ready to jam out on some of our needed functions!

**Comment by RedEagleP1** [comment]
We have such a bot but no voting system: 

Make your own events
Interested people click reaction to indicate they are coming
Remind people who are interested to come automatically

We could: 
(A) Give you the source code to play with and extend 
(B) Talk about open sourcing it

It's well tested, used for years and work fantastic.

**Comment by le-dawg** [comment]
> 

Joining the discussion from outside due to interest. 

Does the released bot track attendence in Discord live calls yet?

**Comment by RedEagleP1** [comment]
The bot we have made does track live attendance.

**Comment by mrmetaverse** [comment]
Archiving to done, as we have bots in place. The key here was automation, which we lost when the main library was no longer supported.
