### ISSUE TITLE
Draft Vision and Mission 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#72]
## Getting to the core of why we are here

Today an important question was asked during our weekly meeting. _What is our Vision?_ 

We often talk about it, but we could benefit from writing it down together. 

**I propose that next working session we take 10-15 minutes to review these two draft vision and mission statements, and make any changes or tweaks as necessary, and let's put it in our readme.**

 
### A Vision statement is critical to inspiring change
It tells you where we are heading. What our future state looks like, and _why_ all of this work matters. 

### A Mission statement is tactical to create real change 
It speaks of our purpose, and the work we do to make change. 

### Drafts

**One (draft) vision is to bolster an open, user-centered, interoperable metaverse for everyone.**

**One draft mission is to research, discover, and deliver protocol for an open, user-centered interoperable metaverse.**

What's one thing you would tweak or improve?

**Comment by mrmetaverse** [comment]
additional info: "A Mission Statement defines the company's business, its objectives and its approach to reach those objectives." as sometimes its easy to confuse or conflate mission and vision.

**Comment by mrmetaverse** [comment]
Evo shared this today. Adding here to review on plane tonight. https://www.forbes.com/sites/forbesbusinesscouncil/2020/04/14/how-to-find-a-massive-transformative-purpose-for-you-and-your-organization/?sh=26df39533fa4

**Comment by VirtDEE** [comment]
Comments on Vision:
It should be easy to understand for folks not belonging to SW culture and need to drop human bias: a proposal as below:
A collaboration towards accessible and interoperable _Metavese_ for all.

(All here means, humans, AI, APIs, etc)

**Comment by mrmetaverse** [comment]
Thanks for sharing @VirtDEE, for the vision, what if we remove the words "A collaboration towards," and just test "An accessible, interoperable Metaverse"?

**Comment by mrmetaverse** [comment]
Add to next weeks agenda (10min)
- add what we agree on to readme 
- continue discussion after publishing and make refinements as needed

**Comment by mrmetaverse** [comment]
move away from explicitly stating "user centered" as we are not solely focused on users at OMI. Its a balance.

**Comment by John-Nagle** [comment]
Let me suggest some principles which served the Internet Engineering Task Force well.

- Rough consensus and running code. [Classic paper on that. ](https://courses.cs.duke.edu//common/compsci092/papers/govern/consensus.pdf)
 
- At least two implementations must interoperate before finalizing a standard.

This reduces getting lost in philosophical and theological questions, which is not helpful when your job is to make A talk to B. That's what "interoperable" means.

**Comment by mrmetaverse** [comment]
> Let me suggest some principles which served the Internet Engineering Task Force well.
> 
> * Rough consensus and running code. [Classic paper on that. ](https://courses.cs.duke.edu//common/compsci092/papers/govern/consensus.pdf)
> * At least two implementations must interoperate before finalizing a standard.
> 
> This reduces getting lost in philosophical and theological questions, which is not helpful when your job is to make A talk to B. That's what "interoperable" means.

Great points! Both of which are part of our formal process 😊
https://github.com/omigroup/omigroup/blob/main/PROCESS.md#proposal-refinement-adoption-and-merging-of-efforts

**Comment by mrmetaverse** [comment]
We bolster an open, interoperable Metaverse for anyone, inspired by the collaborative efforts of our community.

- Mal mentioned that the word Metaverse may throw people off. 
- Will suggested XR technologies that would enable an open metaverse for everybody. (all of the technologies interconnected that create the greater sum of the whole) 
- Evo suggested that we can define the metaverse together as we see fit, we could help change the mental image in others minds through effective communication x visualization (mapping) of interoperability. 
- Jesse suggested changing everyone to anyone. 
- Change the community to our community 
- Lyuma: OMI contains the M. I think its ok to mention an "_undefined_" term like metaverse in our vision, and dive deeper into what we mean later. 
- Will suggested stating what we mean by Open Metaverse. This could be a future exercise. 
  - Q: Do we want to state our alignment with "the 7 rules of the metaverse"?

**Comment by mrmetaverse** [comment]
VOTE: We bolster the metaverse as an open and interoperable resource for anyone, inspired by the collaborative efforts of the community.

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/140103679-ccd3b074-eddf-4e3d-a0b1-7dc56725aec5.png)

Vote passed!

**Comment by mrmetaverse** [comment]
NOTE: one user put all of the voting options there, so if you see anything over 1 then it is a vote. That 1 down thumb is a placeholder to vote, not a vote for no.

**Comment by robertlong** [comment]
Votes For:
![image](https://user-images.githubusercontent.com/1753624/142248813-0ac9373d-a1ad-492f-9117-1a3e1565787e.png)

Votes Against:
![image](https://user-images.githubusercontent.com/1753624/142248998-86cfe3d5-7a56-4bc9-838c-48a83d2ddf7e.png)
(Jesse started the poll, so the thumbs down vote isn't actually a vote against)

Abstentions:
![image](https://user-images.githubusercontent.com/1753624/142248904-eb0a7535-30de-439c-9c9f-622ab064a248.png)
