### ISSUE TITLE
Form working group for possible OMI VKet booth 

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#89]
We have an opportunity to hose an OMI booth at the next VR Chat Virtual Market VKet event. A channel has been created in discord and our group is seeking volunteers for this effort. 

```
To decide now (by September 12):
 - who owns this project (will be responsible for uploading & should be an active "New User" level or higher VrChat player) others can collab via git. (There is a lottery & either I or Saracen will also apply as a backup.)
- we need to pick the top 3 venues to exhibit at. We can make a survey where we can choose or just pick a few (if anyone wants to review the concept art above and nominate a few of their favorites in chat, that would be awesome!)
[note that different styles of venues: being a booth in a bigger space; or being in a 10x10x10 mini-world that you "pop" into one at a time]
- the person (google account) who submits will need to be responsible to pay JPY 3300 next week or later. I will be happy to cover the costs.
``` 
_-  lyuma_ 

It looks like our deadline for this it _today Sunday 9/12/21_ could we confirm?

**Comment by lyuma** [comment]
The deadline is now in 8 hours, JST.
The task only requires someone to log into https://winter2021.vket.com/ with a google account, fill out the three world selections and hit confirm.

We didn't receive any consensus on which worlds to pick, so we can just pick randomly / arbitrarily... any of the general worlds are probably best.

I do not think the VRChat requirement is strictly necessary at this phase, and it should be easy to do if necessary.

**Comment by mrmetaverse** [comment]
I assume we missed this one. How often do these happen? Seems to be more and more frequent. Maybe we plan to do the next one?

**Comment by mrmetaverse** [comment]
We are signed up! Thanks Koolala 

- update: lottery hasn't happened yet

**Comment by mrmetaverse** [comment]
In todays meeting we asked if we could see the booth, or experience it in VR as a group next week (before VKET)

**Comment by mrmetaverse** [comment]
please see OMI-VKET-PLANNING channel in discord 
![image](https://user-images.githubusercontent.com/63426722/144288700-237d0735-b451-45d7-a834-7163c6eb6baf.png)

**Comment by mrmetaverse** [comment]
https://twitter.com/mrmetaverse/status/1467344491841560580/photo/3

**Comment by lyuma** [comment]
I would like to formally request if @Koolala can update the catalog link here:
https://winter2021.vket.com/en/circle/411

To add a "catalog item" pointing to https://omigroup.org

It would be nice if it says Open Metaverse Interoperability somewhere in the booth description. OMI or OMI Group are not quite descriptive enough for those unfamiliar with this working group.

**Comment by mrmetaverse** [comment]
Koolala and the V-Sekai team really hooked up OMI with a VKET booth in Virtual Market (VR Chat) 
You can find it in the [Vket2021 Poppin' Jump - Rich Gold](https://vrchat.com/home/world/wrld_4f73aad2-6887-4f85-9fb7-7c075562b849) Server in the "Alpha" Room.

**Comment by lyuma** [comment]
Some of my friends did not realize that the booth was literally born in the metaverse.

As an aside, it would be cool if this explainer image could be linked in the webpage, since it's actually mindblowing once you realize that what the booth represents and that it was collaboratively created cross platform in the metaverse:

![Anyland->Neos->VRChat->Virtual Market](https://user-images.githubusercontent.com/39946030/145261973-7c146833-1575-4c63-b538-836268ef1ea2.png)
