### ISSUE TITLE
Establish OMI Community Development Working Group

### ISSUE THREAD

**Issue by robertlong** [omigroup/omigroup#92]
# OMI Community Development Working Group

The Community Development Working Group will meet on a regular basis and discuss strategy for OMI partnerships, outreach, and co-development.

**Comment by mrmetaverse** [comment]
Do we need a vote on this? I think we already have this group by now, but is it formally called this? Or is this related to the fiscal development group?

**Comment by mrmetaverse** [comment]
No longer relevant due to new groups like delegates and champions
