### ISSUE TITLE
Move OMI HackMD to use github sync

### ISSUE THREAD

**Issue by robertlong** [omigroup/omigroup#93]
@madjin noted that HackMD can sync to a github repo which would really improve the visibility of our meeting notes. I'll try to set that up before next week's meeting.

**Comment by mrmetaverse** [comment]
Yeah I use it all the time for my daily notes! I guess we could create a folder in our omigroup/omi repo, and just start adding the .md files to that folder each time? I don't know that we can add the notes to the agenda automatically, but syncing hackmd and github is pretty straightforward.

**Comment by mrmetaverse** [comment]
deprioritizing as we use the threaded discussions for our meeting notes, and other ad-hoc meetings use hackmd. If we want integration we can set it up as needed!
