### ISSUE TITLE
Let's talk about virtual World location exif data for screenshots captured inside of Virtual Worlds.

### ISSUE THREAD

**Issue by mrmetaverse** [omigroup/omigroup#96]
Let's also discuss the Privacy aspects: like how do we keep that from being used maliciously? 

Is this a project worth pursuing? 

https://www.exif.org/Exif2-2.PDF

**Comment by mrmetaverse** [comment]
Jin mentioned how much he likes taking photos inside of virtual worlds.

**Comment by John-Nagle** [comment]
The notation used in Second Life and Open Simulator is

REGIONNAME/X/Y/Z

plus a GRIDNAME field. 

There's a URL representation of this, defined in [this document.](http://opensimulator.org/wiki/Browser_Protocol_Handler). Browsers can be configured to launch a metaverse viewer for such URLs, as defined therein.

**Comment by mrmetaverse** [comment]
bump - will archive next groom

**Comment by mrmetaverse** [comment]
archive
